disabled = false
languageCode = "it"
languageName = "Italiano"
weight = 3
title = "Talasius Matrimonio"

[params]
  displayName = "IT"
  isoCode = "it"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

# [params.author]
#   name = "Your name here"
#   email = "youremail@example.com"
#   image = "img/blowfish_logo.png"
#   imageQuality = 96
#   headline = "I'm only human"
#   bio = "A little bit about you"