disabled = false
languageCode = "it"
languageName = "Italiano"
weight = 3
title = "Giulia & Jannis"

[params]
  displayName = "IT"
  isoCode = "it"
  rtl = false
  dateFormat = "2 Giugno 2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

 [params.author]
   name = "Giulia & Jannis"
   email = "giuliabuizza@protonmail.com"
   image = "img/logo.png"
   imageQuality = 96
   headline = "20 Giugno 2026"
#   bio = "A little bit about you"