disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Giulia & Jannis"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "January 2, 2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

 [params.author]
   name = "Giulia & Jannis"
   email = "jannis.dickmann@protonmail.com"
   image = "img/logo.png"
   imageQuality = 96
   headline = "June 20, 2026"
#   bio = "A little bit about you"
