[[main]]
  name = "Home"
  pageRef = "_index.it.md"
  weight = 10

[[main]]
  name = "Agenda"
  pageRef = "agenda/index.it.md"
  weight = 20

[[main]]
  name = "Luogo"
  pageRef = "location/event/index.it.md"
  weight = 30

[[main]]
  name = "Luogo dell'evento"
  parent = "Luogo"
  pageRef = "location/event/index.it.md"
  weight = 10

[[main]]
  name = "Lago d'Iseo"
  parent = "Luogo"
  pageRef = "location/iseo/index.it.md"
  weight = 20

[[main]]
  name = "Altre attivit√†"
  parent = "Luogo"
  pageRef = "location/activities/_index.it.md"
  weight = 30

[[main]]
  name = "Fotografie"
  pageRef = "photos/index.it.md"
  weight = 40
