[[main]]
name = "Startseite"
pageRef = "_index.de.md"
weight = 10

[[main]]
name = "Wo"
pageRef = "location/index.de.md"
weight = 20

[[main]]
name = "Wann"
pageRef = "agenda/index.de.md"
weight = 30

[[main]]
name = "Nützliche Informationen"
weight = 40

[[main]]
name = "Anreise"
parent = "Nützliche Informationen"
pageRef = "info/arrival/index.de.md"
weight = 10

[[main]]
name = "Unterkunft"
parent = "Nützliche Informationen"
pageRef = "info/accommodation/index.de.md"
weight = 20

[[main]]
name = "Reiseführer"
parent = "Nützliche Informationen"
pageRef = "info/activities/index.de.md"
weight = 30

[[footer]]
name = "Impressum"
pageRef = "legal/impress"
weight = 10

[[footer]]
name = "Datenschutz"
pageRef = "legal/privacy"
weight = 20
