[[main]]
name = "Where"
pageRef = "location/index.en.md"
weight = 10

[[main]]
name = "When"
pageRef = "agenda/index.en.md"
weight = 20

[[main]]
name = "Arrival"
pageRef = "arrival/index.en.md"
weight = 30

[[main]]
name = "Accommodation"
pageRef = "accommodation/index.en.md"
weight = 40

[[main]]
name = "Travel Guide"
pageRef = "activities/index.de.md"
weight = 50

[[main]]
name = "Brescia"
parent = "Travel Guide"
pageRef = "activities/brescia/index.en.md"
weight = 10

[[main]]
name = "Hiking"
parent = "Travel Guide"
pageRef = "activities/hikes/index.en.md"
weight = 20

[[main]]
name = "Lake Iseo"
parent = "Travel Guide"
pageRef = "in/activities/iseo/index.en.md"
weight = 30

[[main]]
name = "Lake Garda"
parent = "Travel Guide"
pageRef = "activities/garda/index.en.md"
weight = 40

[[main]]
name = "Cities"
parent = "Travel Guide"
pageRef = "activities/cities/index.en.md"
weight = 50

[[main]]
name = "Wineries"
parent = "Travel Guide"
pageRef = "activities/wine/index.en.md"
weight = 60

[[footer]]
name = "Legal Notice"
pageRef = "legal/impress"
weight = 10

[[footer]]
name = "Privacy Policy"
pageRef = "legal/privacy"
weight = 20
