[[main]]
name = "Home"
pageRef = "index.it.md"
weight = 5

[[main]]
name = "Dove"
pageRef = "location/index.it.md"
weight = 10

[[main]]
name = "Quando"
pageRef = "agenda/index.it.md"
weight = 20

[[main]]
name = "Arrivo"
pageRef = "arrival/index.it.md"
weight = 30

[[main]]
name = "Alloggio"
pageRef = "accommodation/index.it.md"
weight = 40

[[main]]
name = "Guida turistica"
pageRef = "activities/index.it.md"
weight = 50

[[main]]
name = "Brescia"
parent = "Guida turistica"
pageRef = "activities/brescia/index.it.md"
weight = 10

[[main]]
name = "Escursionismo"
parent = "Guida turistica"
pageRef = "activities/hikes/index.it.md"
weight = 20

[[main]]
name = "Lago d'Iseo"
parent = "Guida turistica"
pageRef = "activities/iseo/index.it.md"
weight = 30

[[main]]
name = "Lago di Garda"
parent = "Guida turistica"
pageRef = "activities/garda/index.it.md"
weight = 40

[[main]]
name = "Citt√†"
parent = "Guida turistica"
pageRef = "activities/cities/index.it.md"
weight = 50

[[main]]
name = "Cantine"
parent = "Guida turistica"
pageRef = "activities/wine/index.it.md"
weight = 60

[[footer]]
name = "Note legali"
pageRef = "legal/impress"
weight = 10

[[footer]]
name = "Privacy"
pageRef = "legal/privacy"
weight = 20
