[[main]]
name = "Home"
pageRef = "_index.it.md"
weight = 10

[[main]]
name = "Quando"
pageRef = "agenda/index.it.md"
weight = 20

[[main]]
name = "Dove"
pageRef = "location/index.it.md"
weight = 30

[[main]]
name = "Informazioni Utili"
weight = 40

[[main]]
name = "Arrivo"
parent = "Informazioni Utili"
pageRef = "info/arrival/index.it.md"
weight = 10

[[main]]
name = "Alloggio"
parent = "Informazioni Utili"
pageRef = "info/accommodation/index.it.md"
weight = 20

[[main]]
name = "Brescia & Iseo"
parent = "Informazioni Utili"
pageRef = "info/brescia-iseo/index.it.md"
weight = 30

[[main]]
name = "Attivit√†"
parent = "Informazioni Utili"
pageRef = "info/activities/index.it.md"
weight = 40
