[[main]]
  name = "Home"
  pageRef = "_index.en.md"
  weight = 10

[[main]]
  name = "Location"
  pageRef = "location.en.md"
  weight = 20

[[main]]
  name = "Pictures"
  pageRef = "pictures.en.md"
  weight = 30
