[[main]]
name = "Home"
pageRef = "_index.en.md"
weight = 10

[[main]]
name = "Where"
pageRef = "location/index.en.md"
weight = 20

[[main]]
name = "When"
pageRef = "agenda/index.en.md"
weight = 30

[[main]]
name = "Useful Information"
weight = 40

[[main]]
name = "Arrival"
parent = "Useful Information"
pageRef = "info/arrival/index.en.md"
weight = 10

[[main]]
name = "Accommodation"
parent = "Useful Information"
pageRef = "info/accommodation/index.en.md"
weight = 20

[[main]]
name = "Brescia & Iseo"
parent = "Useful Information"
pageRef = "info/brescia-iseo/index.en.md"
weight = 30

[[main]]
name = "Activities"
parent = "Useful Information"
pageRef = "info/activities/index.en.md"
weight = 40
