[[main]]
  name = "Home"
  pageRef = "_index.de.md"
  weight = 10

[[main]]
  name = "Location"
  pageRef = "location.de.md"
  weight = 20

[[main]]
  name = "Bilder"
  pageRef = "pictures.de.md"
  weight = 30
