[[main]]
name = "Home"
pageRef = "index.de.md"
weight = 5

[[main]]
name = "Wo"
pageRef = "location/index.de.md"
weight = 10

[[main]]
name = "Wann"
pageRef = "agenda/index.de.md"
weight = 20

[[main]]
name = "Anreise"
pageRef = "arrival/index.de.md"
weight = 30

[[main]]
name = "Unterkunft"
pageRef = "accommodation/index.de.md"
weight = 40

[[main]]
name = "Reiseführer"
pageRef = "activities/index.de.md"
weight = 50

[[main]]
name = "Brescia"
parent = "Reiseführer"
pageRef = "activities/brescia/index.de.md"
weight = 10

[[main]]
name = "Wandern"
parent = "Reiseführer"
pageRef = "activities/hikes/index.de.md"
weight = 20

[[main]]
name = "Iseosee"
parent = "Reiseführer"
pageRef = "activities/iseo/index.de.md"
weight = 30

[[main]]
name = "Gardasee"
parent = "Reiseführer"
pageRef = "activities/garda/index.de.md"
weight = 40

[[main]]
name = "Städte"
parent = "Reiseführer"
pageRef = "activities/cities/index.de.md"
weight = 50

[[main]]
name = "Weingüter"
parent = "Reiseführer"
pageRef = "activities/wine/index.de.md"
weight = 60

[[footer]]
name = "Impressum"
pageRef = "legal/impress"
weight = 10

[[footer]]
name = "Datenschutz"
pageRef = "legal/privacy"
weight = 20
