[[main]]
  name = "Home"
  pageRef = "_index.it.md"
  weight = 10

[[main]]
  name = "Location"
  pageRef = "location.it.md"
  weight = 20

[[main]]
  name = "Foto"
  pageRef = "pictures.it.md"
  weight = 30
