backend:
  name: github
  repo: numynox/talasius
  branch: main
  auth_type: implicit
  app_id: Ov23liB0PosC6QC5yJAd
  auth_url: https://github.com/login/oauth/authorize
  base_url: https://numynox.github.io/talasius/
  # Optionally, use a more secure workflow
  # publish_mode: editorial_workflow

media_folder: "static/uploads"  # Images will be uploaded here
public_folder: "/uploads"       # Public path for the images

# Example collection for your guest instructions and other pages
collections:
  - name: "page"
    label: "Pages"
    folder: "content"
    create: true
    i18n: true # Enable translation/multilingual support
    fields:
      - {label: "Title", name: "title", widget: "string", i18n: true}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown", i18n: true}